# $FirebaseSDKVersion = '8.5.0'
# $RNFirebaseAsStaticFramework = true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Republic' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RepublicTests' do
    inherit! :complete
    # Pods for testing
  end
  #pod 'OpenSSL-Universal', '~>1.0.2.20'
  # React Native Maps dependencies
 rn_maps_path = '../node_modules/react-native-maps'
 pod 'react-native-google-maps', :path => rn_maps_path
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  #use_flipper!({'Flipper' => '0.87.0' , 'Flipper-Folly' => '2.5.3' , 'Flipper-RSocket' => '1.3.1' })
  #use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Republic-tvOS' do
  # Pods for Republic-tvOS

  target 'Republic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
