export const SET_USER_DETAIL = 'SET_USER_DETAIL'
export const SET_PRODUCT_CATEGORIES = 'SET_PRODUCT_CATEGORIES'
export const SET_PRODUCT_ITEMS = 'SET_PRODUCT_ITEMS'
export const SET_PRODUCT_MANUFACTURERS = 'SET_PRODUCT_MANUFACTURERS'
export const SET_PRODUCT_CALIBERS = 'SET_PRODUCT_CALIBERS'
export const SET_PRODUCT_ACTIONS = 'SET_PRODUCT_ACTIONS'
export const SET_PRODUCT_CONDITIONS = 'SET_PRODUCT_CONDITIONS'
export const SET_CREDIT_CARDS = 'SET_CREDIT_CARDS'
export const SET_REPORTS = 'SET_REPORTS'
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION'

//orders
export const SET_ALL_ORDERS = 'SET_ALL_ORDERS'

//groups
export const SET_MY_GROUPS = 'SET_MY_GROUPS'
export const SET_MY_JOINED_GROUPS = 'SET_MY_JOINED_GROUPS'


